fabricante:
    path:     /
    defaults: { _controller: "FabricanteBundle:fabricante:index" }

fabricante_show:
    path:     /{id}/show
    defaults: { _controller: "FabricanteBundle:fabricante:show" }

fabricante_new:
    path:     /new
    defaults: { _controller: "FabricanteBundle:fabricante:new" }

fabricante_create:
    path:     /create
    defaults: { _controller: "FabricanteBundle:fabricante:create" }
    methods:  POST

fabricante_edit:
    path:     /{id}/edit
    defaults: { _controller: "FabricanteBundle:fabricante:edit" }

fabricante_update:
    path:     /{id}/update
    defaults: { _controller: "FabricanteBundle:fabricante:update" }
    methods:  [POST, PUT]

fabricante_delete:
    path:     /{id}/delete
    defaults: { _controller: "FabricanteBundle:fabricante:delete" }
    methods:  [POST, DELETE]
