procedencia:
    path:     /
    defaults: { _controller: "FabricanteBundle:procedencia:index" }

procedencia_show:
    path:     /{id}/show
    defaults: { _controller: "FabricanteBundle:procedencia:show" }

procedencia_new:
    path:     /new
    defaults: { _controller: "FabricanteBundle:procedencia:new" }

procedencia_create:
    path:     /create
    defaults: { _controller: "FabricanteBundle:procedencia:create" }
    methods:  POST

procedencia_edit:
    path:     /{id}/edit
    defaults: { _controller: "FabricanteBundle:procedencia:edit" }

procedencia_update:
    path:     /{id}/update
    defaults: { _controller: "FabricanteBundle:procedencia:update" }
    methods:  [POST, PUT]

procedencia_delete:
    path:     /{id}/delete
    defaults: { _controller: "FabricanteBundle:procedencia:delete" }
    methods:  [POST, DELETE]
