DsCorp\Personal\PersonalBundle\Entity\personal:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '30'
        apePat:
            type: string
            length: '30'
            column: ape_pat
        apeMat:
            type: string
            length: '30'
            column: ape_mat
        telefono1:
            type: string
            length: '10'
            column: telefono_1
        email:
            type: string
            length: '50'
        fechaCreacion:
            type: datetime
            column: fecha_creacion
        dechaModificacion:
            type: datetime
            column: decha_modificacion
        idCreacion:
            type: integer
            column: id_creacion
        idModificacion:
            type: integer
            column: id_modificacion
    manyToOne:
        puesto:
            targetEntity: DsCorp\Personal\PersonalBundle\Entity\puesto
            mappedBy: personal
    manyToOne:
        empresa: 
            targetEntity: DsCorp\Empresa\EmpresaBundle\Entity\empresa
            mappedBy: personal
    oneToMany:
        direccion_personal:
            targetEntity: DsCorp\Personal\PersonalBundle\Entity\direccion_personal
            mappedBy: personal
    manyToOne:
        estatus:
            targetEntity: DsCorp\General\GeneralBundle\Entity\estatus
            mappedBy: personal
    oneToMany:
        equipo:
            targetEntity: DsCorp\Equipo\EquipoBundle\Entity\equipo
            mappedBy: personal
    oneToMany:
        usuarios:
            targetEntity: DsCorp\Personal\PersonalBundle\Entity\usuarios
            mappedBy: personal
    lifecycleCallbacks: {  }
