DsCorp\Personal\PersonalBundle\Entity\puesto:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        puesto:
            type: string
            length: '20'
    oneToMany:
        personal:
            targetEntity: DsCorp\Personal\PersonalBundle\Entity\personal
            mappedBy: puesto
    lifecycleCallbacks: {  }
