DsCorp\Fabricante\FabricanteBundle\Entity\fabricante:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        razonSocial:
            type: string
            length: '50'
            column: razon_social
        rfc:
            type: string
            length: '15'
        telefono1:
            type: string
            length: '15'
            column: telefono_1
        telefono2:
            type: string
            length: '15'
            column: telefono_2
        email:
            type: string
            length: '50'
        paginaWeb:
            type: string
            length: '50'
            column: pagina_web
        fechaCreacion:
            type: datetime
            column: fecha_creacion
        fechaModificacion:
            type: datetime
            column: fecha_modificacion
        idCreacion:
            type: integer
            column: id_creacion
        idModificacion:
            type: integer
            column: id_modificacion
    oneToMany:
        procedencia:
            targetEntity: DsCorp\Fabricante\FabricanteBundle\Entity\procedencia
            mappedBy: fabricante
    manyToOne:
        direccion_fabricante:
            targetEntity: DsCorp\Fabricante\FabricanteBundle\Entity\direccion_fabricante
            mappedBy: fabricante
    lifecycleCallbacks: {  }
