personal:
    path:     /
    defaults: { _controller: "PersonalBundle:personal:index" }

personal_show:
    path:     /{id}/show
    defaults: { _controller: "PersonalBundle:personal:show" }

personal_new:
    path:     /new
    defaults: { _controller: "PersonalBundle:personal:new" }

personal_create:
    path:     /create
    defaults: { _controller: "PersonalBundle:personal:create" }
    methods:  POST

personal_edit:
    path:     /{id}/edit
    defaults: { _controller: "PersonalBundle:personal:edit" }

personal_update:
    path:     /{id}/update
    defaults: { _controller: "PersonalBundle:personal:update" }
    methods:  [POST, PUT]

personal_delete:
    path:     /{id}/delete
    defaults: { _controller: "PersonalBundle:personal:delete" }
    methods:  [POST, DELETE]
